apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: khofesh/orders
          imagePullPolicy: Never
          env:
            - name: MONGO_URI
              value: "mongodb://orders-mongo-srv:27017/orders"
            - name: MONGO_URI_SESSION
              value: "mongodb://orders-mongo-srv:27017/session"
            - name: RABBIT_USER
              valueFrom:
                secretKeyRef:
                  name: rabbit-user
                  key: RABBIT_USER
            - name: RABBIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbit-password
                  key: RABBIT_PASSWORD
            - name: RABBIT_URL
              value: "rabbit"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: orders-srv
spec:
  selector:
    app: orders
  type: ClusterIP
  ports:
    - name: orders
      protocol: TCP
      port: 3000
      targetPort: 3000
